---
title: 컴파일러 오류 CS1626
ms.date: 07/20/2015
f1_keywords:
- CS1626
helpviewer_keywords:
- CS1626
ms.assetid: 3ba03383-eb24-4fd8-bf40-8b0f7d6baf0d
ms.openlocfilehash: 1263fbd4d6591b1f231e38400c680b549ba5654e
ms.sourcegitcommit: 9b552addadfb57fab0b9e7852ed4f1f1b8a42f8e
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 04/23/2019
ms.locfileid: "61686228"
---
# <a name="compiler-error-cs1626"></a>컴파일러 오류 CS1626
catch 절이 포함된 try 블록의 본문에서는 값을 생성할 수 없습니다.  
  
 yield 문은 try 블록과 연결된 catch 절이 있는 경우 try 블록에 사용할 수 없습니다. 이 오류를 방지 하려면 yield 문을 try/catch/finally 블록 내부에서 외부로 이동 하거나 catch 블록을 제거 합니다.
  
 다음 샘플에서는 CS1626을 생성합니다.  
  
```csharp  
// CS1626.cs  
using System.Collections;  
  
class C : IEnumerable  
{  
   public IEnumerator GetEnumerator()  
   {  
      try  
      {  
         yield return this;  // CS1626  
      }  
      catch  
      {  
  
      }  
      finally
      {
      
      }
   }  
}  
  
public class CMain  
{  
   public static void Main() { }  
}  
```
