---
title: "' GoTo <labelname>' 올바르지 때문에 '<labelname>'는 'Try', 'Catch' 또는 'Finally' 문을이 문을 포함 하지 않는 내부"
ms.date: 07/20/2015
f1_keywords:
- bc30754
- vbc30754
helpviewer_keywords:
- BC30754
ms.assetid: 2eefc7fb-fdf0-41e9-bf60-c3bc93580e14
ms.openlocfilehash: f9acfd18e15ff715ca81c5eb163ff0b31a64252b
ms.sourcegitcommit: 2701302a99cafbe0d86d53d540eb0fa7e9b46b36
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 04/28/2019
ms.locfileid: "64646062"
---
# <a name="goto-labelname-is-not-valid-because-labelname-is-inside-a-try-catch-or-finally-statement-that-does-not-contain-this-statement"></a>' GoTo \<labelname >' 올바르지 때문에 '\<labelname >'는 'Try', 'Catch' 또는 'Finally' 문을이 문을 포함 하지 않는 내부
`Try...Catch...Finally` 블록으로 분기할 수 없습니다.  
  
 **오류 ID:** BC30754  
  
## <a name="to-correct-this-error"></a>이 오류를 해결하려면  
  
- 레이블이 `Try...Catch...Finally` 블록 앞에 오도록 코드 구조를 바꿉니다.  
  
## <a name="see-also"></a>참고자료

- [Try...Catch...Finally 문](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)
