---
title: "'Catch' 블록에 도달 하지 않은, 때문에 '<name1>'에서 상속'<name2>'"
ms.date: 07/20/2015
f1_keywords:
- BC42029
- vbc42029
helpviewer_keywords:
- BC42029
ms.assetid: 4bc84a84-ec7e-49db-8794-4fb71d36d5c0
ms.openlocfilehash: fe716108281b3df64c3d444c54bee8dea3fcb82f
ms.sourcegitcommit: 2701302a99cafbe0d86d53d540eb0fa7e9b46b36
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 04/28/2019
ms.locfileid: "64755861"
---
# <a name="catch-block-never-reached-because-name1-inherits-from-name2"></a>'Catch' 블록에 도달 하지 않은, 때문에 '\<name1 >'에서 상속 '\<name2 >'
코드 내의 `Catch` 블록에 도달하지 않습니다.  
  
 이 메시지는 기본적으로 경고입니다. 경고를 숨기거나 오류로 처리하는 방법에 대한 자세한 내용은 [Configuring Warnings in Visual Basic](/visualstudio/ide/configuring-warnings-in-visual-basic)을 참조하세요.  
  
 **오류 ID:** BC42029  
  
## <a name="to-correct-this-error"></a>이 오류를 해결하려면  
  
- 불필요한 `Catch` 블록을 제거합니다.  
  
## <a name="see-also"></a>참고자료

- [Try/catch 블록을 사용 하 여 예외를 catch 하는 방법](../../standard/exceptions/how-to-use-the-try-catch-block-to-catch-exceptions.md)
- [Try...Catch...Finally 문](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)
